name: Create production promotion pull request
on:
  pull_request:
    branches:
    - master

jobs:
  compare-changes:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install VGS CLI
        run: |
          pip3 install vgs-cli
      - name: Create service_account.yaml file
        run: |
          echo "clientId: $VGS_CLIENT_ID" > service_account.yaml
          echo "clientSecret: $VGS_CLIENT_SECRET" >> service_account.yaml
        env:
          VGS_CLIENT_ID: ${{ secrets.VGS_CLIENT_ID }}
          VGS_CLIENT_SECRET: ${{ secrets.VGS_CLIENT_SECRET }}
      - name: Apply VGS Service Account
        run: vgs apply service-account -O AC4NjboQbJ2RurwUbEZZTezW -f service_account.yaml          
      - name: Diff Vault config
        run: |
          for file in $(ls tnt*yaml);
          do
            vgs get routes --vault ${file/.yaml/} > ${file}.applied;
            diff -u ${file}.applied ${file} || echo "found a diff"
          done
        # env:
        #   VGS_CLIENT_ID: ${{ secrets.VGS_CLIENT_ID }}
        #   VGS_CLIENT_SECRET: ${{ secrets.VGS_CLIENT_SECRET }}
